name: Integrations
on:
  push:
    branches:
      - master
jobs:
  browserstack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        uses: ianwalter/bsl@v2.0.1
        with:
          args: yarn
      - name: Lint
        uses: ianwalter/bsl@v2.0.1
        with:
          args: yarn lint
      - name: Test
        uses: ianwalter/bsl@v2.0.1
        with:
          args: yarn test
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
