name: Changeset
on:
  pull_request:
    types: [labeled]
jobs:
  changeset:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.1.0
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Changeset
        uses: ianwalter/add-changeset@v1.2.2
        with:
          github_token: ${{ secrets.GH_PAT }}
          before_commit: pnpm i -r --frozen-lockfile=false
