name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:15.4-buster
      options: --network-alias testHost
    timeout-minutes: 10
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      chrome:
        image: selenium/node-chrome:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test bff
        run: cd packages/bff; yarn test:ci
      # TODO:
      # - name: Test bff-webdriver
      #   run: npm run test:webdriver
  playwright:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/playwright:v2.2.0
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Test bff
        run: yarn test:playwright
