name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.0.0
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pnpm i
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test:ci
