name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/pnpm:v1.1.0
      options: --network-alias testHost
    timeout-minutes: 10
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      chrome:
        image: selenium/node-chrome:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pnpm i -r
      - name: Lint
        run: pnpm lint
      - name: Test bff
        run: pnpm test:bff
      - name: Test bff-webdriver
        run: pnpm test:webdriver
  playwright:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/playwright:v1.1.1
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pnpm i -r
      - name: Test bff
        run: pnpm test:playwright
